// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc620.Warbots2019.elevator;

import edu.wpi.first.wpilibj.Encoder;
import edu.wpi.first.wpilibj.SpeedController;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

/**
 *
 */
public class SparkEncoderElevator extends Elevator {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private SpeedController motor;
    private Encoder encoder;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    // Initialize your subsystem here
    public SparkEncoderElevator(int leftMotor1Port, int leftMotor2Port, 
        int rightMotor1Port, int rightMotor2Port) {

        

        /*motor = new Spark(1);
        addChild("Motor",motor);
        motor.setInverted(false);

        motor = new Spark(2);
        addChild("Motor",motor);
        motor.setInverted(false);
        
        motor = new Spark(3);
        addChild("Motor",motor);
        motor.setInverted(false);
        
        motor = new Spark(4);
        addChild("Motor",motor);
        motor.setInverted(false);
        
        encoder = new Encoder(4, 5, false, EncodingType.k4X);
        addChild("Encoder",encoder);
        encoder.setDistancePerPulse(1.0);
        encoder.setPIDSourceType(PIDSourceType.kDisplacement);
        */
    
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    
    
        // Use these to get going:
        // setSetpoint() -  Sets where the PID controller should move the system
        //                  to
        // enable() - Enables the PID controller.
    }

    @Override
    public void initDefaultCommand() {
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
        setDefaultCommand(new ControlElevatorWithJoystick(this));
    }
}
