Version 2.0

---
Children:
- Children:
  - Children:
    - Children:
      - Children:
        - Children: []
          Properties:
            Type: !!robotbuilder.data.properties.ChoicesProperty
              choices: &id001 [Victor, Jaguar, Talon, VictorSP, PWMTalonSRX, Spark,
                SD540, PWMVictorSPX, DMC60]
              default: Spark
              name: Type
              validators: null
              value: Spark
            Output Channel (PWM): !!robotbuilder.data.properties.ChoicesProperty
              choices: &id002 ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10',
                '11', '12', '13', '14', '15', '16', '17', '18', '19']
              default: '0'
              name: Output Channel (PWM)
              validators: &id003 [PWMOutput]
              value: '0'
            Inverted: !!robotbuilder.data.properties.BooleanProperty {default: false,
              name: Inverted, validators: null, value: false}
          Base: Speed Controller
          Name: Left Front Motor
        - Children: []
          Properties:
            Type: !!robotbuilder.data.properties.ChoicesProperty
              choices: *id001
              default: Spark
              name: Type
              validators: null
              value: Spark
            Output Channel (PWM): !!robotbuilder.data.properties.ChoicesProperty
              choices: *id002
              default: '0'
              name: Output Channel (PWM)
              validators: *id003
              value: '1'
            Inverted: !!robotbuilder.data.properties.BooleanProperty {default: false,
              name: Inverted, validators: null, value: false}
          Base: Speed Controller
          Name: Left Rear Motor
        Properties:
          SpeedController4: !!robotbuilder.data.properties.ChildSelectionProperty {
            default: null, name: SpeedController4, type: PIDOutput, validators: null,
            value: null}
          SpeedController3: !!robotbuilder.data.properties.ChildSelectionProperty {
            default: null, name: SpeedController3, type: PIDOutput, validators: null,
            value: null}
          SpeedController2: !!robotbuilder.data.properties.ChildSelectionProperty
            default: 1
            name: SpeedController2
            type: PIDOutput
            validators: &id004 [SpeedControllerGroup, ChildDropdownSelected]
            value: Left Rear Motor
          SpeedController1: !!robotbuilder.data.properties.ChildSelectionProperty
            default: 0
            name: SpeedController1
            type: PIDOutput
            validators: &id005 [SpeedControllerGroup, ChildDropdownSelected]
            value: Left Front Motor
        Base: Speed Controller Group
        Name: Left Motors
      - Children:
        - Children: []
          Properties:
            Type: !!robotbuilder.data.properties.ChoicesProperty
              choices: *id001
              default: Spark
              name: Type
              validators: null
              value: Spark
            Output Channel (PWM): !!robotbuilder.data.properties.ChoicesProperty
              choices: *id002
              default: '0'
              name: Output Channel (PWM)
              validators: *id003
              value: '2'
            Inverted: !!robotbuilder.data.properties.BooleanProperty {default: false,
              name: Inverted, validators: null, value: false}
          Base: Speed Controller
          Name: Right Front Motor
        - Children: []
          Properties:
            Type: !!robotbuilder.data.properties.ChoicesProperty
              choices: *id001
              default: Spark
              name: Type
              validators: null
              value: Spark
            Output Channel (PWM): !!robotbuilder.data.properties.ChoicesProperty
              choices: *id002
              default: '0'
              name: Output Channel (PWM)
              validators: *id003
              value: '3'
            Inverted: !!robotbuilder.data.properties.BooleanProperty {default: false,
              name: Inverted, validators: null, value: false}
          Base: Speed Controller
          Name: Right Rear Motor
        Properties:
          SpeedController4: !!robotbuilder.data.properties.ChildSelectionProperty {
            default: null, name: SpeedController4, type: PIDOutput, validators: null,
            value: null}
          SpeedController3: !!robotbuilder.data.properties.ChildSelectionProperty {
            default: null, name: SpeedController3, type: PIDOutput, validators: null,
            value: null}
          SpeedController2: !!robotbuilder.data.properties.ChildSelectionProperty
            default: 1
            name: SpeedController2
            type: PIDOutput
            validators: *id004
            value: Right Rear Motor
          SpeedController1: !!robotbuilder.data.properties.ChildSelectionProperty
            default: 0
            name: SpeedController1
            type: PIDOutput
            validators: *id005
            value: Right Front Motor
        Base: Speed Controller Group
        Name: Right Motors
      Properties:
        Right Motor: !!robotbuilder.data.properties.ChildSelectionProperty
          default: 1
          name: Right Motor
          type: PIDOutput
          validators: [RobotDrive2, ChildDropdownSelected]
          value: Right Motors
        Maximum Output: !!robotbuilder.data.properties.DoubleProperty {default: 1,
          name: Maximum Output, validators: null, value: 1.0}
        Left Motor: !!robotbuilder.data.properties.ChildSelectionProperty
          default: 0
          name: Left Motor
          type: PIDOutput
          validators: [RobotDrive2, ChildDropdownSelected]
          value: Left Motors
        Safety Expiration Time: !!robotbuilder.data.properties.DoubleProperty {default: 0.1,
          name: Safety Expiration Time, validators: null, value: 0.1}
        Safety Enabled: !!robotbuilder.data.properties.BooleanProperty {default: true,
          name: Safety Enabled, validators: null, value: true}
      Base: Differential Drive
      Name: Differential Drive
    Properties:
      Send to SmartDashboard: !!robotbuilder.data.properties.BooleanProperty {default: false,
        name: Send to SmartDashboard, validators: null, value: false}
      Default command parameters: !!robotbuilder.data.properties.ParametersProperty
        default: []
        name: Default command parameters
        validators: null
        value: []
      Default Command: !!robotbuilder.data.properties.TypeSelectionProperty {default: None,
        name: Default Command, type: Command, validators: null, value: Drive With Joystick}
      Constants: !!robotbuilder.data.properties.ConstantsProperty
        default: []
        name: Constants
        validators: null
        value: []
    Base: Subsystem
    Name: Drive Train
  Properties: {}
  Base: Subsystems
  Name: Subsystems
- Children:
  - Children: []
    Properties:
      Number: !!robotbuilder.data.properties.ChoicesProperty
        choices: ['0', '1', '2', '3', '4', '5']
        default: 1
        name: Number
        validators: [Joystick]
        value: '0'
    Base: Joystick
    Name: Operator Controller
  Properties: {}
  Base: OI
  Name: Operator Interface
- Children:
  - Children: []
    Properties:
      Autonomous Selection: !!robotbuilder.data.properties.BooleanProperty {default: false,
        name: Autonomous Selection, validators: null, value: false}
      Parameters: !!robotbuilder.data.properties.ParametersProperty
        default: []
        name: Parameters
        validators: null
        value: []
      Run When Disabled: !!robotbuilder.data.properties.BooleanProperty {default: false,
        name: Run When Disabled, validators: null, value: false}
      Requires: !!robotbuilder.data.properties.TypeSelectionProperty {default: None,
        name: Requires, type: Subsystem, validators: null, value: None}
      Parameter presets: !!robotbuilder.data.properties.ParameterSetProperty
        default: &id006 []
        name: Parameter presets
        validators: null
        value: *id006
      Button on SmartDashboard: !!robotbuilder.data.properties.BooleanProperty {default: true,
        name: Button on SmartDashboard, validators: null, value: true}
    Base: Command
    Name: Autonomous Command
  - Children: []
    Properties:
      Autonomous Selection: !!robotbuilder.data.properties.BooleanProperty {default: false,
        name: Autonomous Selection, validators: null, value: false}
      Parameters: !!robotbuilder.data.properties.ParametersProperty
        default: []
        name: Parameters
        validators: null
        value: []
      Run When Disabled: !!robotbuilder.data.properties.BooleanProperty {default: false,
        name: Run When Disabled, validators: null, value: false}
      Requires: !!robotbuilder.data.properties.TypeSelectionProperty {default: None,
        name: Requires, type: Subsystem, validators: null, value: Drive Train}
      Parameter presets: !!robotbuilder.data.properties.ParameterSetProperty
        default: &id007 []
        name: Parameter presets
        validators: null
        value: *id007
      Button on SmartDashboard: !!robotbuilder.data.properties.BooleanProperty {default: true,
        name: Button on SmartDashboard, validators: null, value: true}
    Base: Command
    Name: Drive With Joystick
  Properties: {}
  Base: Commands
  Name: Commands
Properties:
  Export Commands: !!robotbuilder.data.properties.BooleanProperty {default: true,
    name: Export Commands, validators: null, value: true}
  Autonomous command parameters: !!robotbuilder.data.properties.ParametersProperty
    default: []
    name: Autonomous command parameters
    validators: null
    value: []
  Java Package: !!robotbuilder.data.properties.StringProperty {default: org.usfirst.frc0000,
    name: Java Package, validators: null, value: org.jmhsrobotics}
  Use Default Java Package: !!robotbuilder.data.properties.BooleanProperty {default: true,
    name: Use Default Java Package, validators: null, value: true}
  Team Number: !!robotbuilder.data.properties.IntegerProperty {default: 0, name: Team Number,
    validators: null, value: 620}
  Export Subsystems: !!robotbuilder.data.properties.BooleanProperty {default: true,
    name: Export Subsystems, validators: null, value: true}
  Simulation World File: !!robotbuilder.data.properties.StringProperty {default: /usr/share/frcsim/worlds/GearsBotDemo.world,
    name: Simulation World File, validators: null, value: /usr/share/frcsim/worlds/GearsBotDemo.world}
  Wiring file location: !!robotbuilder.data.properties.FileProperty {default: 'C:\Users\Owner\',
    extension: null, folder: true, name: Wiring file location, validators: null, value: ..\}
  Export Directory: !!robotbuilder.data.properties.FileProperty {default: 'C:\Users\Owner\FRCProjects',
    extension: null, folder: true, name: Export Directory, validators: null, value: ..\}
  Autonomous Command: !!robotbuilder.data.properties.TypeSelectionProperty {default: None,
    name: Autonomous Command, type: Command, validators: null, value: Autonomous Command}
Base: Robot
Name: Warbots2019
