// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc620.Warbots2019.robot;

import java.util.ArrayList;
import java.util.Arrays;

import org.usfirst.frc620.Warbots2019.mechanisms.DeployScoringMechanismCommand;
import org.usfirst.frc620.Warbots2019.mechanisms.StowScoringMechanismCommand;
import org.usfirst.frc620.Warbots2019.utility.ControlReader;

import edu.wpi.first.wpilibj.GenericHID;
import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.buttons.JoystickButton;
import edu.wpi.first.wpilibj.command.Command;

public class AxisSpecification
{

    public enum AnalogControlType
    {
        CONTROL_UNDEFINED,
        CONTROL_LEFT_JOYSTICK,
        CONTROL_RIGHT_JOYSTICK,
        CONTROL_LEFT_TRIGGER,
        CONTROL_RIGHT_TRIGGER,
        CONTROL_DPAD
    };
    
    public enum UserDesignation
    {
        USER_UNDEFINED,
        USER_DRIVER,
        USER_SCORER
    };

    public enum ControlAxis
    {
        AXIS_UNDEFINED,
        AXIS_UP_DOWN,
        AXIS_LEFT_RIGHT
    };
    
    public enum UserControlValueType
    {
        UCVT_UNDEFINED,
        UCVT_ROBOT_SPEED,         // -1.0 to 1.0
        UCVT_ROBOT_ROTATION_RATE, 
        UCVT_ELEVATOR_SPEED,     
        UCVT_DEPLOY_RATE
    };

    UserDesignation      userDesignation;
    AnalogControlType    controlType;
    ControlAxis          axis;
    UserControlValueType valueType;

    public boolean isValidAxisSpecification(AxisSpecification axisSpec)
    {
        // Only JOYSTICKS need distintion between X/Y axes - and therefore it's OK
        // if axis is not defined for non-joystick controls like DPad.
        boolean needsXY = ((axisSpec.controlType == AnalogControlType.CONTROL_LEFT_JOYSTICK) || 
            (axisSpec.controlType == AnalogControlType.CONTROL_RIGHT_JOYSTICK));
        
        return ((!needsXY || (needsXY && (axisSpec.axis != ControlAxis.AXIS_UNDEFINED))) && 
            (axisSpec.controlType != AnalogControlType.CONTROL_UNDEFINED) && 
            (axisSpec.userDesignation != UserDesignation.USER_UNDEFINED) && 
            (axisSpec.valueType != UserControlValueType.UCVT_UNDEFINED));
    }

    public static AxisSpecification buildAxisSpecification(String ctrl, String cfgValue)
    {
        AxisSpecification axisSpec = new AxisSpecification();
        axisSpec.controlType = AnalogControlType.CONTROL_UNDEFINED;
        axisSpec.userDesignation = UserDesignation.USER_UNDEFINED;
        axisSpec.valueType = UserControlValueType.UCVT_UNDEFINED;
        axisSpec.axis = ControlAxis.AXIS_UNDEFINED;

        // Set control type
        if (ctrl.contains(".LeftJS."))
        {
            axisSpec.controlType = AnalogControlType.CONTROL_LEFT_JOYSTICK;
        }
        else if (ctrl.contains(".RightJS."))
        {
            axisSpec.controlType = AnalogControlType.CONTROL_RIGHT_JOYSTICK;
        }
        else if (ctrl.endsWith(".LeftTrigger"))
        {
            axisSpec.controlType = AnalogControlType.CONTROL_LEFT_TRIGGER;
        }
        else if (ctrl.endsWith(".RightTrigger"))
        {
            axisSpec.controlType = AnalogControlType.CONTROL_RIGHT_TRIGGER;
        }
        else if (ctrl.contains(".DPad."))
        {
            axisSpec.controlType = AnalogControlType.CONTROL_DPAD;
        }

        // Set axis
        if (ctrl.endsWith(".Y"))
        {
            axisSpec.axis = ControlAxis.AXIS_UP_DOWN;
        }
        else if (ctrl.endsWith(".X"))
        {
            axisSpec.axis = ControlAxis.AXIS_LEFT_RIGHT;
        }

        // Set value type
        if (cfgValue.endsWith("OI.robot.speed"))
        {
            axisSpec.valueType = UserControlValueType.UCVT_ROBOT_SPEED;
        }
        else if (cfgValue.endsWith("OI.robot.rotation_rate"))
        {
            axisSpec.valueType = UserControlValueType.UCVT_ROBOT_ROTATION_RATE;
        }
        else if (cfgValue.endsWith("OI.elevator.speed")) // Example
        {
            axisSpec.valueType = UserControlValueType.UCVT_ELEVATOR_SPEED;
        }
        else if (cfgValue.endsWith("OI.mech.deploy_rate")) // Example
        {
            axisSpec.valueType = UserControlValueType.UCVT_DEPLOY_RATE;
        }
        return axisSpec;
    }

    public String toString()
    {
        String ret = "";

        if (userDesignation == UserDesignation.USER_UNDEFINED)
        {
            ret += "USER_UNDEFINED:";
        }
        else if (userDesignation == UserDesignation.USER_DRIVER)
        {
            ret += "DRIVER:";
        }
        else if (userDesignation == UserDesignation.USER_SCORER)
        {
            ret += "SCORER:";
        };

        if (controlType == AnalogControlType.CONTROL_UNDEFINED)
        {
            ret += "CONTROL_UNDEFINED:";
        }
        else if (controlType == AnalogControlType.CONTROL_LEFT_JOYSTICK)
        {
            ret += "LEFT_JOYSTICK:";
        }
        else if (controlType == AnalogControlType.CONTROL_RIGHT_JOYSTICK)
        {
            ret += "RIGHT_JOYSTICK:";
        }
        else if (controlType == AnalogControlType.CONTROL_LEFT_TRIGGER)
        {
            ret += "LEFT_TRIGGER:";
        }
        else if (controlType == AnalogControlType.CONTROL_RIGHT_TRIGGER)
        {
            ret += "RIGHT_TRIGGER:";
        }
        else if (controlType == AnalogControlType.CONTROL_DPAD)
        {
            ret += "DPAD:";
        }

        if (axis == ControlAxis.AXIS_UNDEFINED)
        {
            ret += "AXIS_UNDEFINED:";
        }
        else if (axis == ControlAxis.AXIS_UP_DOWN)
        {
            ret += "UP_DOWN:";
        }
        else if (axis == ControlAxis.AXIS_LEFT_RIGHT)
        {
            ret += "LEFT_RIGHT:";
        }
        
        if (valueType == UserControlValueType.UCVT_UNDEFINED)
        {
            ret += "UCVT_UNDEFINED";
        }
        else if (valueType == UserControlValueType.UCVT_ROBOT_SPEED)
        {
            ret += "ROBOT_SPEED";
        }
        else if (valueType == UserControlValueType.UCVT_ROBOT_ROTATION_RATE)
        {
            ret += "ROBOT_ROTATION_RATE";
        }
        else if (valueType == UserControlValueType.UCVT_ELEVATOR_SPEED)
        {
            ret += "ELEVATOR_SPEED";
        }
        else if (valueType == UserControlValueType.UCVT_DEPLOY_RATE)
        {
            ret += "DEPLOY_RATE";
        }
    
        return ret;
    }
};

